const localVideoBaseUrl = '/videos';
const productionVideoBaseUrl = (
  import.meta.env.VITE_VIDEO_BASE_URL
  || 'https://media.githubusercontent.com/media/dong77-shisan/-/main/public/videos'
).replace(/\/$/, '');

const videoUrl = (fileName) =>
  `${import.meta.env.DEV ? localVideoBaseUrl : productionVideoBaseUrl}/${fileName}`;

export const siteConfig = {
  heroVideo: '', // 例如：'/media/hero-showreel.mp4'
};

export const projectCategories = [
  { id: 'bilibili', label: 'B站视频系列', en: 'BILIBILI' },
  { id: 'game', label: '游戏击杀系列', en: 'GAME' },
  { id: 'ai', label: 'AI视频系列', en: 'AI VIDEO' },
  { id: 'other', label: '其他系列', en: 'OTHERS' },
];

export const projects = [
  {
    id: 'bilibili-vibe-coding',
    index: '01',
    category: 'bilibili',
    title: '秒哒商单',
    titleNote: '视频为跨部门合作，个人制作07分17分至10分18秒',
    subtitle: '知识科普 / 中长视频',
    year: '2026',
    role: '剪辑 · MG 动画 · 声音设计',
    image: '/work/bilibili-vibe-coding.jpg',
    bilibili: 'BV1khMX63EjU',
    video: '',
    theme: 'acid',
    description: '围绕 Vibe Coding 实战竞赛展开，以中长视频形式呈现从创意构想到 App 完成的完整过程。',
  },
  {
    id: 'bilibili-course-lead',
    index: '02',
    category: 'bilibili',
    title: '课程引流',
    titleNote: '个人负责后期全流程',
    subtitle: 'B站视频 / 商业内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-bilibili-course-lead.png',
    video: videoUrl('bilibili-course-lead.mp4'),
    theme: 'acid',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'bilibili-flova-commercial',
    index: '03',
    category: 'bilibili',
    title: 'Flova商单',
    titleNote: '个人负责后期全流程',
    subtitle: 'B站视频 / 商业内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-bilibili-flova-commercial.png',
    video: videoUrl('bilibili-flova-commercial.mp4'),
    theme: 'acid',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'bilibili-agnes-douyin',
    index: '04',
    category: 'bilibili',
    title: 'Agnes 产品商单',
    titleNote: '个人负责后期全流程',
    subtitle: '抖音视频 / 商业内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-bilibili-agnes-douyin.png',
    douyin: '7650058150666552831',
    video: '',
    theme: 'acid',
    description: 'Agnes 产品商单，个人负责视频后期全流程。',
  },
  {
    id: 'bilibili-deepseek-commercial',
    index: '05',
    category: 'bilibili',
    title: 'DeepSeek商单',
    titleNote: '个人负责后期全流程',
    subtitle: 'B站视频 / 商业内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-bilibili-deepseek-commercial.png',
    video: videoUrl('bilibili-deepseek-commercial.mp4'),
    theme: 'acid',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'game-01',
    index: '01',
    category: 'game',
    title: '游戏1',
    titleNote: '个人负责后期全流程',
    subtitle: '游戏击杀 / 高光剪辑',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-game-01.png',
    video: videoUrl('game-01.mp4'),
    theme: 'orange',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'game-02',
    index: '02',
    category: 'game',
    title: '游戏2',
    titleNote: '个人负责后期全流程',
    subtitle: '游戏击杀 / 高光剪辑',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-game-02.png',
    video: videoUrl('game-02.mp4'),
    theme: 'orange',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'game-03',
    index: '03',
    category: 'game',
    title: '游戏3',
    titleNote: '个人负责后期全流程',
    subtitle: '游戏击杀 / 高光剪辑',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-game-03.png',
    video: videoUrl('game-03.mp4'),
    theme: 'orange',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'ai-123',
    index: '01',
    category: 'ai',
    title: '123',
    titleNote: '个人负责后期全流程',
    subtitle: 'AI视频 / 生成内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-ai-123.png',
    video: videoUrl('ai-123.mp4'),
    theme: 'violet',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'ai-aigc',
    index: '02',
    category: 'ai',
    title: 'aigc',
    titleNote: '个人负责后期全流程',
    subtitle: 'AI视频 / 生成内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-ai-aigc.png',
    video: videoUrl('ai-aigc.mp4'),
    theme: 'violet',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'other-real-estate-ip-01',
    index: '01',
    category: 'other',
    title: '地产IP口播1',
    titleNote: '个人负责后期全流程',
    subtitle: '人物口播 / 商业内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-other-real-estate-ip-01.png',
    video: videoUrl('other-real-estate-ip-01.mp4'),
    theme: 'blue',
    description: '个人负责视频后期全流程。',
  },
  {
    id: 'other-real-estate-ip-02',
    index: '02',
    category: 'other',
    title: '地产IP口播2',
    titleNote: '个人负责后期全流程',
    subtitle: '人物口播 / 商业内容',
    year: '2026',
    role: '个人负责后期全流程',
    image: '/work/thumb-other-real-estate-ip-02.png',
    video: videoUrl('other-real-estate-ip-02.mp4'),
    theme: 'blue',
    description: '个人负责视频后期全流程。',
  },
];

export const experience = [
  {
    period: '2026.05 — NOW',
    company: '鲸海拾贝科技（厦门）有限公司',
    role: '视频剪辑师',
    detail: '服务百万粉及百大 UP 主，独立完成 AI 知识科普、商业合作与课程内容的中长视频后期。',
  },
  {
    period: '2023.08 — 2025.12',
    company: '厦门信归星文化有限公司',
    role: 'IP 剪辑 / 运营',
    detail: '负责创始人 IP、品牌带货与地产商务内容，覆盖策划、拍摄、剪辑、投流及直播间搭建。',
  },
  {
    period: '2022.07 — 2023.07',
    company: '厦门延开度信息咨询有限公司',
    role: '游戏剪辑 / 小组管理',
    detail: '打造 CSGO 主播短视频内容与起号方案，管理 4–6 人剪辑小组并负责培训、审片。',
  },
];
